[package]
name = "unified-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
zkvm = []
testutils = ["dep:arbitrary"]

[dependencies]
agglayer-primitives.workspace = true
agglayer-tries.workspace = true

arbitrary = { workspace = true, optional = true }
bincode.workspace = true
hex-literal = "0.4"
hex.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
serde_with = { version = "3" }
sp1-core-machine.workspace = true
sp1-prover.workspace = true
sp1-sdk.workspace = true
thiserror.workspace = true
tiny-keccak = { version = "2.0", features = ["keccak"] }

[dev-dependencies]
agglayer-primitives = { workspace = true, features = ["testutils"] }
rand = "0.9.0"
rs_merkle = { version = "1.4", default-features = false }

[lints]
workspace = true
