extend = [
    { path = "scripts/make/Makefile.ci.toml" },
    { path = "scripts/make/Makefile.proto.toml" },
]

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false
