[package]
name = "agglayer-tries"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agglayer-primitives.workspace = true

serde.workspace = true
serde_with.workspace = true
thiserror.workspace = true

[lints]
workspace = true
