[package]
name = "agglayer-bincode"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bincode.workspace = true
serde.workspace = true

[dev-dependencies]
sp1-sdk.workspace = true
